### ISSUE TITLE
Trouble with B4 manifest file EPIC

### ISSUE THREAD

**Issue by RKLAUSH** [hansenlab/minfi#162]
After following steps as decribed in [Manifest file update in minfiEPIC - 21 june 2017](https://github.com/hansenlab/minfi/issues/117)
I keep getting the following warning message:
package ‘IlluminaHumanMethylationEPICanno.ilm10b4.hg1’ is not available (for R version 3.5.0) 

I am not very experienced with R, but I was wondering if am doing something wrong, or if I should just wait a while?

I hope someone knows more and is willing to help!

**Comment by kasperdanielhansen** [comment]
Have you installed the package?

```
source("https://www.bioconductor.org/biocLite.R")
biocLite("IlluminaHumanMethylationEPICanno.ilm10b4.hg19")
```
Note that the output has a missing `9` at the end where it says `hg19`.  Perhaps the only thing wrong is a typo?

**Comment by RKLAUSH** [comment]
Yes the only thing wrong was a typo... thanks for your help!
