### ISSUE TITLE
getAnnotation() details

### ISSUE THREAD

**Issue by nikolayaivanov** [hansenlab/minfi#202]
Hi!
I can't seem to find the descriptions for the column names for the data frame returned by getAnnotation(GRset). The column names are fairly descriptive, but I would like to get more details. For instance, I assume the column named 'Enhancer' indicated whether or not the probe is in an enhancer region. But is it possible to figure out which gene this enhancer corresponds to?

Thank you for your help!

**Comment by kasperdanielhansen** [comment]
The columns are supplied by the group supplying the annotation, which is why its not really documented. In this case, the columns come from Illumina's annotation file. If you figure out a description for these columns I am happy to add them to the package. Closing the issue.
