### ISSUE TITLE
read.metharray.exp function doesn't work

### ISSUE THREAD

**Issue by Aikaterini-Chatzipli** [hansenlab/minfi#213]
Hello minfi developers, 

I am using the minfi package to analyse Illumina EPIC methylation array data. The read.metharray.exp function for RGSet doesn't work for me. Please read error message below. My idat files match the samples on my "Sample Sheet" and therefore, I don't understand the error I got. I'm using R version 3.5.1 and minfi version 1.28.4. Your input will be much appreciated. 

Many thanks, 

Katerina

RGset <- read.metharray.exp(targets = targets, verbose = TRUE, force=TRUE)
Error in read.metharray(basenames = files, extended = extended, verbose = verbose,  : 
  !anyDuplicated(basenames) is not TRUE

**Comment by PeteHaitch** [comment]
The error message is telling you that you have IDAT files with the same name.
Can you see such duplicated rows in your sample sheet?

**Comment by Aikaterini-Chatzipli** [comment]
Actually, I found the problem. I didn't have duplicated rows in my sample sheet. 

Thanks for your response. You can close this ticket. 

Katerina
