### ISSUE TITLE
Upcoming change to DelayedArray::realize()

### ISSUE THREAD

**Issue by hpages** [hansenlab/minfi#256]
Hi Kasper,

In the next few days I'm planning to make a small change to the behavior of `DelayedArray::realize()` that could potentially affect packages that use this function. Looks like **minfi** is one of them, sorry! :wink: 

**What will change?**

Only the behavior of the default `realize()` method will change, and it will change only when the `BACKEND` argument is set to `NULL`. Right now (i.e. in **DelayedArray** <= 0.29.0), `realize(x, BACKEND=NULL)` realizes `x` in memory (as an ordinary array) and returns the in-memory array wrapped in a DelayedArray object. The change I'm considering is to get rid of the DelayedArray wrap, that is, to return the in-memory array naked.

Note that for any other `BACKEND` value, nothing will change, i.e. `realize()` will still be guaranteed to return a DelayedArray derivative (e.g. an HDF5Array object if `BACKEND` is set to `"HDF5Array"`).

**How will this affect your code?**

If it's important for your code that `realize()` _always_ returns a DelayedArray object or derivative, like it does at the moment, then simply replace any call to `realize(...)` with `DelayedArray(realize(...))`. This will preserve the current behavior even after the change. Note that calling the `DelayedArray()` constructor function on a DelayedArray object or derivative is a no-op. In other words, this extra step won't add the DelayedArray wrap again if there's already one.

**Where/when will this change happen?**

I will make this change to the `devel` branch of the **DelayedArray** package in the next few days. It will only (potentially) affect packages [in BioC 3.19](https://bioconductor.org/checkResults/3.19/bioc-LATEST/). Nothing will change in the `RELEASE_3_18` branch of **DelayedArray** (BioC 3.18).

I will try to come up with a PR for **minfi** if I see that the change breaks it. Just wanted to give you a heads-up.

Cheers,
H.

**Comment by PeteHaitch** [comment]
Thanks for the heads up, Hervé.
Can you please explain a bit on the reasons for the change?
Also, when `BACKEND = NULL`, will the in-memory array be an ordinary _matrix_/_array_ or might it be e.g., a _dgCMatrix_ if that was the in-memory seed of the _DelayedArray_?

**Comment by hpages** [comment]
BTW yesterday I looked at the potential impact of this change on **DelayedMatrixStats** and I didn't see any (the code in the package always calls `realize()` with `BACKEND="HDF5Array"`). Hence why I didn't open an issue for **DelayedMatrixStats** :wink:

**Comment by hpages** [comment]
@PeteHaitch I just made the change today. It's in **DelayedArray** 0.29.1. I'll monitor the Bioconductor daily builds this week and make sure to identify any glitch related to this change.

**Comment by hpages** [comment]
Looks like this change didn't cause any problem: https://bioconductor.org/checkResults/3.19/bioc-LATEST/minfi/

Closing this now.

**Comment by PeteHaitch** [comment]
Thanks, Hervé.
